# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(default=b'__COLL__', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CollToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_word', models.TextField(default=b'')),
                ('seq', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=100)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant_app.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(default=b'')),
                ('seq', models.IntegerField(default=-1)),
                ('coll_token', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='variant_app.CollToken')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant_app.Corpus')),
                ('text', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='variant_app.Text')),
            ],
        ),
        migrations.AddField(
            model_name='colltoken',
            name='base_token',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='variant_app.Token'),
        ),
        migrations.AddField(
            model_name='colltoken',
            name='coll_text',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='variant_app.CollText'),
        ),
        migrations.AddField(
            model_name='colltoken',
            name='corpus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='variant_app.Corpus'),
        ),
        migrations.AddField(
            model_name='colltext',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant_app.Corpus'),
        ),
    ]
