# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0002_auto_20170108_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
