# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0004_remove_colltoken_base_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colltoken',
            old_name='base_word',
            new_name='word',
        ),
    ]
