# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0005_auto_20170108_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colltoken',
            name='seq',
            field=models.IntegerField(default=-2),
        ),
    ]
