# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('variant_app', '0006_auto_20170110_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpus',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='text',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
