# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0007_auto_20170111_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='coll_token_seq',
            field=models.IntegerField(default=-1),
        ),
    ]
