# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0008_token_coll_token_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='coll_token',
        ),
    ]
