# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0010_colltoken_variability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colltoken',
            name='variability',
        ),
        migrations.AddField(
            model_name='token',
            name='variability',
            field=models.IntegerField(default=0),
        ),
    ]
