# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0013_auto_20170113_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='variability',
            field=models.FloatField(default=0.0),
        ),
    ]
