# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0014_token_variability'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='author',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
