# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0015_corpus_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
