# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0017_auto_20170118_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
