# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0021_text_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
