# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0022_text_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='author',
            new_name='editor',
        ),
    ]
