# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0023_auto_20170119_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='corpus',
            name='n_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corpus',
            name='preview',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.TextField(default=b''),
        ),
    ]
