# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0024_auto_20170120_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('n_queries', models.IntegerField(default=0)),
            ],
        ),
    ]
