# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:17
from __future__ import unicode_literals

from django.contrib.postgres.operations import TrigramExtension
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0025_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, verbose_name=b'preview'),
        ),
        TrigramExtension(),
    ]
