# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', 'trigram'),
        ('variant_app', '0026_corpus_search_vector'),
    ]

    operations = [
    ]
