# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0027_merge_20170120_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='corpus',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
