# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant_app', '0029_colltoken_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_token_end', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variant_app_block_end', to='variant_app.CollToken')),
                ('coll_token_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_app_block_start', to='variant_app.CollToken')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant_app.Corpus')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant_app.Text')),
                ('token_end', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variant_app_block_end', to='variant_app.Token')),
                ('token_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_app_block_start', to='variant_app.Token')),
            ],
        ),
    ]
